# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Interest.create name:'Sport'
Interest.create name:'Art'
Interest.create name:'Films'
Interest.create name:'Music'
Interest.create name:'Fashion'
Interest.create name:'History'
Interest.create name:'Theatre'
Interest.create name:'T.V'
Interest.create name:'Travelling'
Interest.create name:'Beer'
Interest.create name:'Food'

User.create first_name:'Ben', last_name:'Smith', email:'ben_smith@email.com', gender:'male', looking_for:'female', post_code:'LN8 0PA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

User.create first_name:'Kate', last_name:'Smith', email:'kate_smith@email.com', gender:'female', looking_for:'male', post_code:'LN2 0LA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

User.create first_name:'Shelly', last_name:'Smith', email:'shelly_smith@email.com', gender:'female', looking_for:'female', post_code:'DN8 0GA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 2

User.create first_name:'Steph', last_name:'Smith', email:'steph_smith@email.com', gender:'female', looking_for:'female', post_code:'CB8 0JA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 2

User.create first_name:'Jess', last_name:'Smith', email:'jess_smith@email.com', gender:'female', looking_for:'male', post_code:'LN2 0LA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 3

User.create first_name:'Tom', last_name:'Smith', email:'tom_smith@email.com', gender:'male', looking_for:'female', post_code:'JS8 0PA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 3

User.create first_name:'Gerry', last_name:'Smith', email:'gerry_smith@email.com', gender:'male', looking_for:'male', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 4

User.create first_name:'Mike', last_name:'Smith', email:'mike_smith@email.com', gender:'male', looking_for:'male', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 4

User.create first_name:'Steve', last_name:'Smith', email:'steve_smith@email.com', gender:'male', looking_for:'female', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

User.create first_name:'Mary', last_name:'Smith', email:'mary_smith@email.com', gender:'female', looking_for:'male', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

User.create first_name:'Jeff', last_name:'Smith', email:'Jeff_smith@email.com', gender:'male', looking_for:'female', post_code:'LN8 0PA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 5

User.create first_name:'Claire', last_name:'Smith', email:'claire_smith@email.com', gender:'female', looking_for:'male', post_code:'LN2 0LA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 5

User.create first_name:'Beth', last_name:'Smith', email:'beth_smith@email.com', gender:'female', looking_for:'female', post_code:'DN8 0GA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 2

User.create first_name:'Beyonce', last_name:'Smith', email:'beyonce_smith@email.com', gender:'female', looking_for:'female', post_code:'CB8 0JA', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 2

User.create first_name:'Laura', last_name:'Smith', email:'laura_smith@email.com', gender:'female', looking_for:'male', post_code:'SG4 0HS', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 3

User.create first_name:'Henry', last_name:'Smith', email:'henry_smith@email.com', gender:'male', looking_for:'female', post_code:'SB7 8VN', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 3

User.create first_name:'Lewis', last_name:'Smith', email:'lewis_smith@email.com', gender:'male', looking_for:'male', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 4

User.create first_name:'Alex', last_name:'Smith', email:'alex_smith@email.com', gender:'male', looking_for:'male', post_code:'LG8 4RZ', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 4

User.create first_name:'Paul', last_name:'Smith', email:'paul_smith@email.com', gender:'male', looking_for:'female', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

User.create first_name:'Hannah', last_name:'Smith', email:'hannah_smith@email.com', gender:'female', looking_for:'male', post_code:'LS8 4RT', about_me:'Lo-fi American Apparel sustainable, next level trust fund asymmetrical tousled keffiyeh Kickstarter fashion axe kogi craft beer locavore cray. Kogi asymmetrical DIY, keytar ethnic banh mi distillery vegan Godard meggings PBR&B trust fund crucifix pour-over. Schlitz craft beer farm-to-table iPhone cray, pop-up fap skateboard disrupt literally mustache put a bird on it Intelligentsia. Mumblecore polaroid tofu vegan, iPhone High Life quinoa sriracha authentic artisan DIY. Vinyl crucifix Williamsburg, plaid tattooed selfies McSweeneys wolf stumptown Thundercats flannel fap XOXO mumblecore ethical. Retro +1 ennui bitters mlkshk. Tousled YOLO Wes Anderson, iPhone yr skateboard fixie.

# Carles street art hella, Schlitz mlkshk flexitarian seitan. Shoreditch XOXO Tumblr, Truffaut authentic bicycle rights skateboard Brooklyn Kickstarter church-key asymmetrical Bushwick locavore. Thundercats slow-carb Banksy ugh pour-over beard yr. Etsy umami crucifix Tonx disrupt sriracha. Yr four loko meh, 8-bit pop-up beard banjo literally cliche occupy chia. Odd Future craft beer wayfarers kale chips. Carles PBR synth 8-bit lomo put a bird on it.', password:'password', password_confirmation:'password', interest_ids: 1

